all: SYST.BAZ \
     EDT.FE \
     EDH.FE
     
SYST.BAZ: /ASM/NOYAU/SYST.ASM
	fasm SYST.ASM SYST.BAZ
EDT.FE: /ASM/PROG/EDT.ASM
	fasm EDT.ASM EDT.FE
EDH.FE: /ASM/PROG/EDH.ASM
	fasm EDH.ASM EDH.FE
  
  
